name: signup
version: 1.0.0
auto_build: false
targets:
    - cent6
build:
  dependencies:
    - assets-publish
    - bzip2
    - node
  commands: |
    npm install
    npm run lint
    npm run build
    assets-publish ${PWD}/dist